name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:  
      - master

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '4.7.x' ]
        
    env:
      Solution_Path: Firma_zadanie.sln
      WPF_Project_Path: Firma_zadanie\Firma_zadanie.csproj
      Actions_Allow_Unsecure_Commands: true
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.302'
          
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      
      - name: Build 
        run: msbuild $env:Solution_Path -t:build -restore
